name: GhostMain
version: '${project.version}'
main: de.elia.ghostmain.GhostMain
api-version: 1.18
authors: [ Elia ]
description: The main plugin from the server
website: https://discord.gg/Kpt8kgkhMA
loadbefore:
  - GhostWarp
  - Ghostchat
commands:
  information:
    description: Send information of the Plugin creator.
    aliases:
      - info
      - i
  setpermission:
    description: Set a Permission.
    aliases:
      - setperm
  infopermission:
    description: Send a info of the Playerpermission.
    aliases:
      - informationpermission
      - informationperm
      - infoperm
      - ipermission
      - iperm
  helppermission:
    description: Send a Help about the Permissionsystem.
    aliases:
      - helpperm
  delpermission:
    description: Deleted a Permission of the Player
    aliases: delperm